//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class AplicationModel
	{
		public static int maze_size;
		public static float begin_time;
		public static float end_time;
		public static float time;

		public static bool key = false;

		public AplicationModel ()
		{
			begin_time = 0;
			end_time = 0;
			time = 0;
			key = false;
		}

		public static void clearVariables(){
			begin_time = 0;
			end_time = 0;
			time = 0;
			key = false;
		}
	}
}

